### ISSUE TITLE
yaml to cfg

### ISSUE THREAD

**Issue by LiuWQ0809** [ZJU-lishuang/yolov5_prune#1]
Hello，is there a yaml to cfg script？I'd like to try your yolov5s pruning operation, I'm sorry I didn't find the corresponding cfg file.

**Comment by ZJU-lishuang** [comment]
there is not a yaml to cfg script.

**Comment by LiuWQ0809** [comment]
Thank you very much for sharing. I'll give it a try. You've recently updated some pruning-related content. I'd like to ask what the effect of Slimming pruning on yolov5s is?

**Comment by ZJU-lishuang** [comment]
I think it is useful.
