### ISSUE TITLE
yolov3_slimming迁移到yolov5可以成功的主要原因？

### ISSUE THREAD

**Issue by DaChaoXc** [ZJU-lishuang/yolov5_prune#10]

**Comment by DaChaoXc** [comment]
我试过只添加updateBN函数，稀疏训练失败，就是bn稀疏都是0.5左右，我仔细对比了两个项目的代码，或许work的原因是取消了ema？

**Comment by ZJU-lishuang** [comment]
使用amp后，updateBN函数不起作用，我debug看了一下。
本来amp就不是必要的。

**Comment by DaChaoXc** [comment]
> 使用ema后，updateBN函数不起作用，我debug看了一下。
> 本来ema就不是必要的。

我看训练代码里，test和保存的都是ema.ema.module，那么训练过程和剪枝都是有问题的。

**Comment by ZJU-lishuang** [comment]
笔误，是amp，不是ema >_<

**Comment by ZJU-lishuang** [comment]
混合精度训练有问题
