### ISSUE TITLE
减枝后的model无法在yolov5上运行

### ISSUE THREAD

**Issue by maxiaotian520** [ZJU-lishuang/yolov5_prune#11]
你好，我用自己的数据在这个项目里剪枝后，打算在原yolov5的项目中test，但是报错; 然后我用你在tutorial 里给的8倍通道剪枝的model去跑，结果还是一样。报错如下：
Traceback (most recent call last):
  File "test.py", line 309, in <module>
    test(opt.data,
  File "test.py", line 55, in test
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/home/bai/Desktop/yolov5-v3-test/models/experimental.py", line 118, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
AttributeError: 'collections.OrderedDict' object has no attribute 'float'
请问是model 需要再转换一下格式么？ 但是我看它已经是.pt格式了，实在不知道咋整。

**Comment by ZJU-lishuang** [comment]
可以查看步骤四微调的时候是怎么加载模型的。
使用[Darknet](https://github.com/ZJU-lishuang/yolov5-v3/blob/main/prune_finetune.py#L69)函数利用新生成的模型网络结构文件cfg初始化模型。

原yolov5的项目中test中的模型载入并不适用于剪枝后的模型。

**Comment by maxiaotian520** [comment]
谢谢回复，可是我微调的时候依然报错.
Traceback (most recent call last):
  File "prune_finetune.py", line 509, in <module>
    train(hyp, opt, device, tb_writer)
  File "prune_finetune.py", line 144, in train
    model.load_state_dict(torch.load(opt.weights)['model'])
  File "/home/bai/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Darknet:
	size mismatch for module_list.89.Conv2d.weight: copying a param with shape torch.Size([24, 124, 1, 1]) from checkpoint, the shape in current model is torch.Size([255, 124, 1, 1]).
	size mismatch for module_list.89.Conv2d.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([255]).
	size mismatch for module_list.103.Conv2d.weight: copying a param with shape torch.Size([24, 208, 1, 1]) from checkpoint, the shape in current model is torch.Size([255, 208, 1, 1]).
	size mismatch for module_list.103.Conv2d.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([255]).
	size mismatch for module_list.117.Conv2d.weight: copying a param with shape torch.Size([24, 237, 1, 1]) from checkpoint, the shape in current model is torch.Size([255, 237, 1, 1]).
	size mismatch for module_list.117.Conv2d.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([255]).
这个错误有没有可能是cfg的问题？我在prune的时候，是把你给的cfg里面的classes全部改成了我用的数据集里类的数量，其他的没有改动，是这样么？ 还是说是其他问题引起的？

**Comment by maxiaotian520** [comment]
谢谢回复，可是我在微调的时候依然出现了报错：
Traceback (most recent call last):
  File "prune_finetune.py", line 509, in <module>
    train(hyp, opt, device, tb_writer)
  File "prune_finetune.py", line 144, in train
    model.load_state_dict(torch.load(opt.weights)['model'])
  File "/home/bai/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Darknet:
	size mismatch for module_list.89.Conv2d.weight: copying a param with shape torch.Size([24, 124, 1, 1]) from checkpoint, the shape in current model is torch.Size([255, 124, 1, 1]).
	size mismatch for module_list.89.Conv2d.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([255]).
	size mismatch for module_list.103.Conv2d.weight: copying a param with shape torch.Size([24, 208, 1, 1]) from checkpoint, the shape in current model is torch.Size([255, 208, 1, 1]).
	size mismatch for module_list.103.Conv2d.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([255]).
	size mismatch for module_list.117.Conv2d.weight: copying a param with shape torch.Size([24, 237, 1, 1]) from checkpoint, the shape in current model is torch.Size([255, 237, 1, 1]).
	size mismatch for module_list.117.Conv2d.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([255]).
这有没有可能是cfg问题，因为我也用的是yolov5s的，所以我在prune的时候是把你的yolov5s.cfg文件里的classes的数量改成了我数据集里的类的数量，其他的没有变，是这样么？  还是说是其他原因引起的? 多谢指导！

**Comment by ZJU-lishuang** [comment]
cfg也是需要根据类别调整的

**Comment by dpk3** [comment]
模型剪枝后不能检测
Traceback (most recent call last):
  File "detect.py", line 173, in <module>
    detect()
  File "detect.py", line 34, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/home/d/yolov5-v3-20201224/models/experimental.py", line 137, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
  File "/home/d/yolov5-v3-20201224/modelsori.py", line 342, in fuse
    fused = torch_utils.fuse_conv_and_bn(conv, b)
NameError: name 'torch_utils' is not defined

**Comment by ZJU-lishuang** [comment]
the problem is the fuse function.
I have fix the bug in yolov5-v3.
You can have a try.

**Comment by dpk3** [comment]
> the problem is the fuse function.
> I have fix the bug in [yolov5-v3](https://github.com/ZJU-lishuang/yolov5-v3/commit/6b30529027204fe58c2bb270e31759e8083655e8).
> You can have a try.

很抱歉 好像这里还是不太对，
Traceback (most recent call last):
  File "detect.py", line 172, in <module>
    detect()
  File "detect.py", line 33, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "F:\yolov5-v3-main-0118\models\experimental.py", line 137, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
  File "F:\yolov5-v3-main-0118\modelsori.py", line 342, in fuse
    fused = torch_utils.fuse_conv_and_bn(conv, b)
  File "F:\yolov5-v3-main-0118\utils\torch_utils.py", line 121, in fuse_conv_and_bn
    fusedconv = nn.Conv2d(conv.in_channels,
  File "C:\Users\dpk1.2w\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 771, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
**torch.nn.modules.module.ModuleAttributeError: 'LeakyReLU' object has no attribute 'in_channels'**

**Comment by ZJU-lishuang** [comment]
model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval()) 
中改为
model.append(torch.load(w, map_location=map_location)['model'].float().eval()) 
先去掉fuse这个异常点。

**Comment by yao-zheng-yi** [comment]
> > the problem is the fuse function.
> > I have fix the bug in [yolov5-v3](https://github.com/ZJU-lishuang/yolov5-v3/commit/6b30529027204fe58c2bb270e31759e8083655e8).
> > You can have a try.
> 
> 很抱歉 好像这里还是不太对，
> Traceback (most recent call last):
> File "detect.py", line 172, in
> detect()
> File "detect.py", line 33, in detect
> model = attempt_load(weights, map_location=device) # load FP32 model
> File "F:\yolov5-v3-main-0118\models\experimental.py", line 137, in attempt_load
> model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval()) # load FP32 model
> File "F:\yolov5-v3-main-0118\modelsori.py", line 342, in fuse
> fused = torch_utils.fuse_conv_and_bn(conv, b)
> File "F:\yolov5-v3-main-0118\utils\torch_utils.py", line 121, in fuse_conv_and_bn
> fusedconv = nn.Conv2d(conv.in_channels,
> File "C:\Users\dpw\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 771, in **getattr**
> raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
> **torch.nn.modules.module.ModuleAttributeError: 'LeakyReLU' object has no attribute 'in_channels'**

我也遇到了相同的问题
我使用ZJU-lishuang/yolov5中的test.py和detect.py对微调后得到的模型进行测试的时候，都报这个错误
请问您是怎么解决的？

**Comment by dddmmmyyy1998** [comment]
您好，我也遇到了相同的问题，请问您后续咋解决的呀。因为作者在剪枝的时候的指标计算误差很大，所以想自己试试yolov5的val.py进行验证。也出现了和您一样的问题。

**Comment by dddmmmyyy1998** [comment]
> > > the problem is the fuse function.
> > > I have fix the bug in [yolov5-v3](https://github.com/ZJU-lishuang/yolov5-v3/commit/6b30529027204fe58c2bb270e31759e8083655e8).
> > > You can have a try.
> > 
> > 
> > 很抱歉 好像这里还是不太对，
> > Traceback (most recent call last):
> > File "detect.py", line 172, in
> > detect()
> > File "detect.py", line 33, in detect
> > model = attempt_load(weights, map_location=device) # load FP32 model
> > File "F:\yolov5-v3-main-0118\models\experimental.py", line 137, in attempt_load
> > model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval()) # load FP32 model
> > File "F:\yolov5-v3-main-0118\modelsori.py", line 342, in fuse
> > fused = torch_utils.fuse_conv_and_bn(conv, b)
> > File "F:\yolov5-v3-main-0118\utils\torch_utils.py", line 121, in fuse_conv_and_bn
> > fusedconv = nn.Conv2d(conv.in_channels,
> > File "C:\Users\dpw\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 771, in **getattr**
> > raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
> > **torch.nn.modules.module.ModuleAttributeError: 'LeakyReLU' object has no attribute 'in_channels'**
> 
> 我也遇到了相同的问题 我使用ZJU-lishuang/yolov5中的test.py和detect.py对微调后得到的模型进行测试的时候，都报这个错误 请问您是怎么解决的？

您好，请问您解决了，能告知一下解决方案麽，谢谢！
