### ISSUE TITLE
where is 'prune_finetune.py'?

### ISSUE THREAD

**Issue by wangzhiming68** [ZJU-lishuang/yolov5_prune#12]
I cannot find the script of 'prune_finetune/py' to finetune pruned models.

**Comment by ZJU-lishuang** [comment]
What the version of yolov5 are you using?

**Comment by wangzhiming68** [comment]
yolov5 v2.0

**Comment by ZJU-lishuang** [comment]
[prune_finetune.py](https://github.com/ZJU-lishuang/yolov5/blob/master/prune_finetune.py)

**Comment by wangzhiming68** [comment]
Thank you!

**Comment by dengyanli1985** [comment]
yolov5 v3.0,prune_finetune.py is same?

**Comment by ZJU-lishuang** [comment]
The files are the same.

**Comment by dengyanli1985** [comment]
你这工程简直是个坑哦，下载yolov5_prune运行各种报错，出现最多的utils文件里面的代码，各种缺包。一会儿把yolov5_v4中的utils文件里面的py代码覆盖到yolov5_prune的utils文件里面去。好不容易跑通，发现剪枝后的模型比稀疏化训练出来的模型还要大？这是什么情况。稀疏化训练出来的模型是14.06M，我采用的是slim_prune_yolov5s_8x.py，输出模型prune_0.1_keep_0.01_8x_sparity_to_prune.pt有

26.14M

这工程就像打怪兽闯关，解决一个又一个的问题，结果出来了呢，模型.pt格式转.wts格式还行不通。

**Comment by ZJU-lishuang** [comment]
参考实例流程，该工程只用于剪枝。其它三个步骤都是在yolov5工程上完成的

**Comment by ZJU-lishuang** [comment]
剪枝后的模型没有float32转float16，使用yolov5微调一下就下来了

**Comment by dengyanli1985** [comment]
谢谢你的回复，麻烦问下：
1.剪枝微调后的模型.pt为什么比未剪枝前模型更大？
2.剪枝后的模型，不能转成engine文件，报[E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::482, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
yolov5: /home/yolov5-to-engine/common.hpp:189: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
Aborted (core dumped)这个错误，我查询了一下说是.wts模型有问题，而.wts模型是剪枝后模型.pt转换而来的。

**Comment by ZJU-lishuang** [comment]
1、使用yolov5的剪枝微调后的模型，比未剪枝前的模型小，不会大，可能是没有微调，参数是float32格式保存，还可能是不只保存了权重，还保存了其它的参数导致的。
2、剪枝微调后的模型，可以从onnx转到tensorrt，同组的同事已经转成功了（遗憾的是目前我不负责这块内容），建议参考cfg这种网络格式的文件转换示例，因为剪枝后的模型网络结构在cfg中。yolov5本身的yaml网络结构不适合剪枝。

**Comment by maxiaotian520** [comment]
@ZJU-lishuang 你好，我用的第三版进行剪枝，然后再用剪枝后的cfg进行微调，但是微调时报错：
Traceback (most recent call last):
  File "prune_finetune.py", line 491, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "prune_finetune.py", line 136, in train
    model.load_state_dict(torch.load(opt.weights)['model'])
  File "/home/bai/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Darknet:
	size mismatch for module_list.89.Conv2d.weight: copying a param with shape torch.Size([24, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 128, 1, 1]).
	size mismatch for module_list.89.Conv2d.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([18]).
	size mismatch for module_list.103.Conv2d.weight: copying a param with shape torch.Size([24, 173, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 173, 1, 1]).
	size mismatch for module_list.103.Conv2d.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([18]).
	size mismatch for module_list.117.Conv2d.weight: copying a param with shape torch.Size([24, 94, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 94, 1, 1]).
	size mismatch for module_list.117.Conv2d.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([18]).
Internal process exited
网上说是因为我的cfg文件和pt不匹配，我查了下，确实是，但是我确实用的是剪枝后生成的文件，请问这个问题要怎么办呢？谢谢

**Comment by ZJU-lishuang** [comment]
filters=(classes + 5)x3
when classes == 1,filters == 18
when classes == 3,filters == 24
make sure the class num is right.

**Comment by ZJU-lishuang** [comment]
@maxiaotian520 如果debug程序找到了类别错误，能提供一下是在哪找到的吗

**Comment by maxiaotian520** [comment]
好的，我试试，谢谢！

**Comment by maxiaotian520** [comment]
@ZJU-lishuang  你好，我检查了下，感觉类别这块儿应该没有错啊。我用的是自己的数据集，一共三个类。在做sparsity train的时候，我在models/yolov5s.yaml 中还有数据集data下的yaml 类别都是3。prune的时候， 我基于yolov5s_v3_hand.cfg文件，改了下类别,所有的classes都是3，其他的没动。就改了这些，但是finetune还是这个bug. 还有哪里需要改啊？ 谢谢

**Comment by ZJU-lishuang** [comment]
yolov5s_v3_hand.cfg中yolo的classes改为3，前面一个卷积层层数也要改，你看一下是不是这个问题。
这个cfg改法参考[darknet](https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects)

**Comment by maxiaotian520** [comment]
感谢回复，确实是这里的问题，我把每个yolo上面那层的filter数量改了以后，bug就解决了。

**Comment by maxiaotian520** [comment]
@ZJU-lishuang  你好，还有问题要请教，就是我用finetune后的model进行detect, 就用v3项目里的detect.py，但是发现会报错：
Traceback (most recent call last):
  File "detect.py", line 174, in <module>
    detect()
  File "detect.py", line 33, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/home/bai/Desktop/yolov5_prune/yolov5-v3/models/experimental.py", line 137, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
  File "/home/bai/Desktop/yolov5_prune/yolov5-v3/modelsori.py", line 341, in fuse
    fused = torch_utils.fuse_conv_and_bn(conv, b)
  File "/home/bai/Desktop/yolov5_prune/yolov5-v3/utils/torch_utils.py", line 121, in fuse_conv_and_bn
    fusedconv = nn.Conv2d(conv.in_channels,
  File "/home/bai/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'LeakyReLU' object has no attribute 'in_channels'
感觉好像是model的问题。所以我在想这个是否是Model的格式问题?如果是的话，要怎么去转换格式呢？或者有什么解决方案么？我需要用这个model在摄像头上detect. 多谢

**Comment by yao-zheng-yi** [comment]
> @ZJU-lishuang 你好，还有问题要请教，就是我用finetune后的model进行detect, 就用v3项目里的detect.py，但是发现会报错：
> Traceback (most recent call last):
> File "detect.py", line 174, in
> detect()
> File "detect.py", line 33, in detect
> model = attempt_load(weights, map_location=device) # load FP32 model
> File "/home/bai/Desktop/yolov5_prune/yolov5-v3/models/experimental.py", line 137, in attempt_load
> model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval()) # load FP32 model
> File "/home/bai/Desktop/yolov5_prune/yolov5-v3/modelsori.py", line 341, in fuse
> fused = torch_utils.fuse_conv_and_bn(conv, b)
> File "/home/bai/Desktop/yolov5_prune/yolov5-v3/utils/torch_utils.py", line 121, in fuse_conv_and_bn
> fusedconv = nn.Conv2d(conv.in_channels,
> File "/home/bai/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in **getattr**
> raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
> torch.nn.modules.module.ModuleAttributeError: 'LeakyReLU' object has no attribute 'in_channels'
> 感觉好像是model的问题。所以我在想这个是否是Model的格式问题?如果是的话，要怎么去转换格式呢？或者有什么解决方案么？我需要用这个model在摄像头上detect. 多谢

我遇到了相同的报错，请问您解决了吗？

**Comment by ZJU-lishuang** [comment]
@maxiaotian520 @yao-zheng-yi model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval()) 
改为model.append(torch.load(w, map_location=map_location)['model'].float().eval()) 
目前来看是卷积和bn层融合的时候问题

**Comment by ZJU-lishuang** [comment]
才发现这个问题我处理过[fuse函数](https://github.com/ZJU-lishuang/yolov5_prune/commit/201f147fc81e5ea3110395e723b444276bc424fc#diff-4c25d69d5ee3d0278d3fa8967e34e5a0f11559b8ed2761d3fa403d19a96337c4)

**Comment by yao-zheng-yi** [comment]
> @maxiaotian520 @yao-zheng-yi model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())
> 改为model.append(torch.load(w, map_location=map_location)['model'].float().eval())
> 目前来看是卷积和bn层融合的时候问题

改完还是会报错
Traceback (most recent call last):
  File "test.py", line 504, in <module>
    test(opt.data,
  File "test.py", line 57, in test
    imgsz = check_img_size(imgsz, s=model.stride.max())  # check img_size
  File "/home/cwy/.conda/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Darknet' object has no attribute 'stride'

**Comment by ZJU-lishuang** [comment]
cfg模式下darknet类没有一些配置参数，这个改成原有算出来的值就好了
```python
gs = int(max([8, 16, 32]))
imgsz = check_img_size(imgsz, s=gs)  # check img_size
# imgsz = check_img_size(imgsz, s=model.stride.max())  # check img_size
```

```python
#names = model.module.names if hasattr(model, 'module') else model.names
names = ['1', '2']
```
你看还有没有错

**Comment by yao-zheng-yi** [comment]
> cfg模式下darknet类没有一些配置参数，这个改成原有算出来的值就好了
> 
> ```python
> gs = int(max([8, 16, 32]))
> imgsz = check_img_size(imgsz, s=gs)  # check img_size
> # imgsz = check_img_size(imgsz, s=model.stride.max())  # check img_size
> ```
> 
> ```python
> #names = model.module.names if hasattr(model, 'module') else model.names
> names = ['1', '2']
> ```
> 
> 你看还有没有错

按照你的方法改了一下，这是新的报错信息

`Traceback (most recent call last):
  File "test.py", line 507, in <module>
    test(opt.data,
  File "test.py", line 83, in test
    dataloader = create_dataloader(path, imgsz, batch_size, model.stride.max(), opt,
  File "/home/cwy/.conda/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Darknet' object has no attribute 'stride'
`

model.stride.max()该用什么代替呢？

**Comment by ZJU-lishuang** [comment]
gs

**Comment by ZJU-lishuang** [comment]
> > cfg模式下darknet类没有一些配置参数，这个改成原有算出来的值就好了
> > ```python
> > gs = int(max([8, 16, 32]))
> > imgsz = check_img_size(imgsz, s=gs)  # check img_size
> > # imgsz = check_img_size(imgsz, s=model.stride.max())  # check img_size
> > ```
> > 
> > 
> > ```python
> > #names = model.module.names if hasattr(model, 'module') else model.names
> > names = ['1', '2']
> > ```
> > 
> > 
> > 你看还有没有错
> 
> 按照你的方法改了一下，这是新的报错信息
> 
> `Traceback (most recent call last): File "test.py", line 507, in <module> test(opt.data, File "test.py", line 83, in test dataloader = create_dataloader(path, imgsz, batch_size, model.stride.max(), opt, File "/home/cwy/.conda/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__ raise ModuleAttributeError("'{}' object has no attribute '{}'".format( torch.nn.modules.module.ModuleAttributeError: 'Darknet' object has no attribute 'stride' `
> 
> model.stride.max()该用什么代替呢？

gs

**Comment by yao-zheng-yi** [comment]
> cfg模式下darknet类没有一些配置参数，这个改成原有算出来的值就好了
> 
> ```python
> gs = int(max([8, 16, 32]))
> imgsz = check_img_size(imgsz, s=gs)  # check img_size
> # imgsz = check_img_size(imgsz, s=model.stride.max())  # check img_size
> ```
> 
> ```python
> #names = model.module.names if hasattr(model, 'module') else model.names
> names = ['1', '2']
> ```
> 
> 你看还有没有错

请忽略上面的回复，那是个傻问题，已经解决了。
我已经用test.py测试出了微调后模型的mAP值。
非常感谢您的帮助，提前祝您春节快乐

**Comment by ZJU-lishuang** [comment]
> > cfg模式下darknet类没有一些配置参数，这个改成原有算出来的值就好了
> > ```python
> > gs = int(max([8, 16, 32]))
> > imgsz = check_img_size(imgsz, s=gs)  # check img_size
> > # imgsz = check_img_size(imgsz, s=model.stride.max())  # check img_size
> > ```
> > 
> > 
> > ```python
> > #names = model.module.names if hasattr(model, 'module') else model.names
> > names = ['1', '2']
> > ```
> > 
> > 
> > 你看还有没有错
> 
> 请忽略上面的回复，那是个傻问题，已经解决了。
> 我已经用test.py测试出了微调后模型的mAP值。
> 非常感谢您的帮助，提前祝您春节快乐

happy new year

**Comment by maxiaotian520** [comment]
按你说的，我也改出来了，真的太感谢了！ 新年快乐！
