### ISSUE TITLE
'Conv2d' object has no attribute 'conv'

### ISSUE THREAD

**Issue by yao-zheng-yi** [ZJU-lishuang/yolov5_prune#13]
你好
我尝试使用自己的数据集训练模型，按照readme的流程，在使用8倍通道剪枝的时候出现了问题。
Traceback (most recent call last):
  File "slim_prune_yolov5s_8x.py", line 342, in <module>
    copy_weight_v4(modelyolov5, model)
  File "slim_prune_yolov5s_8x.py", line 23, in copy_weight_v4
    copy_conv(cspnet1.cv2, model.module_list[3])
  File "slim_prune_yolov5s_8x.py", line 13, in copy_conv
    conv_dst[0] = conv_src.conv
  File "/home/cwy/.conda/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Conv2d' object has no attribute 'conv'

其中，cfg文件我是复制yolov5s_hand.cfg，修改了class，filters和anchors三个参数
data文件的内容如下：
classes= 10
train  = /data/cwy/CardNumber/yolov5_random/train.txt
valid  = /data/cwy/CardNumber/yolov5_random/test.txt
names = data/CardNumber.names
backup = /data/cwy/CardNumber/yolov5_random/

改了很久也没能改对，请问这个问题该如何解决

**Comment by yao-zheng-yi** [comment]
File "slim_prune_yolov5s_8x.py", line 23, in copy_weight_v4
copy_conv(cspnet1.cv2, model.module_list[3])
copy_weight_v4这个函数是需要在基础训练和稀疏化训练的时候使用yolov5的v4版本训练吗？
ZJU-lishuang/yolov5里的yolov5s.yaml和最新版本的yolov5s.yaml有些不同，ultralytics/yolov5中的yolov5s.yaml在backbone和head中使用C3代替了BottleneckCSP，而ZJU-lishuang/yolov5中的yolov5s.yaml使用的依然是BottleneckCSP
这个对训练是否会有影响，我的错误是因为C3代替了BottleneckCSP导致的吗？

**Comment by yao-zheng-yi** [comment]
你好，我将slim_prune_yolov5s_8x.py中的YOLOV5_V4=True改为了 YOLOV5_V4=False
    YOLOV5_V4=False
    if YOLOV5_V4:
        #yolov5-v4
        copy_weight_v4(modelyolov5, model)
    else:
        #yolov5-v3 yolov5-v2
        copy_weight(modelyolov5, model)
上面问题成功解决，但是map的值非常低
这是剪枝的两个参数值，global_percent=0.1   layer_keep=0.01
+------------+----------+----------+
| Metric     | Before   | After    |
+------------+----------+----------+
| mAP        | 0.181912 | 0.000000 |
| Parameters | 7279367  | 6775415  |
| Inference  | 0.0266   | 0.0261   |
+------------+----------+----------+
before才0.18，after直接是0，在进行稀疏化训练时，测试验证集得到的map在0.95左右
![results](https://user-images.githubusercontent.com/41265163/107172691-f94c3f00-6a00-11eb-975b-7c2c0b6281a6.png)
请问为什么map的值会这么奇怪

**Comment by ZJU-lishuang** [comment]
yolov5第四版网络结构改了，代码有变动

**Comment by ZJU-lishuang** [comment]
稀疏化训练后，权重图是怎么样的，有没有被压缩到y轴
[示例](https://github.com/tanluren/yolov3-channel-and-layer-pruning/blob/master/data/img/bn.jpg)

**Comment by yao-zheng-yi** [comment]
> 稀疏化训练后，权重图是怎么样的，有没有被压缩到y轴
> [示例](https://github.com/tanluren/yolov3-channel-and-layer-pruning/blob/master/data/img/bn.jpg)

感谢回复，请教一下如何得到权重图？

**Comment by ZJU-lishuang** [comment]
> 教一下如何得到权重图？

用tensorboard打开看

**Comment by ZJU-lishuang** [comment]
> 你好，我将slim_prune_yolov5s_8x.py中的YOLOV5_V4=True改为了 YOLOV5_V4=False
> YOLOV5_V4=False
> if YOLOV5_V4:
> #yolov5-v4
> copy_weight_v4(modelyolov5, model)
> else:
> #yolov5-v3 yolov5-v2
> copy_weight(modelyolov5, model)
> 上面问题成功解决，但是map的值非常低
> 这是剪枝的两个参数值，global_percent=0.1 layer_keep=0.01
> +------------+----------+----------+
> | Metric | Before | After |
> +------------+----------+----------+
> | mAP | 0.181912 | 0.000000 |
> | Parameters | 7279367 | 6775415 |
> | Inference | 0.0266 | 0.0261 |
> +------------+----------+----------+
> before才0.18，after直接是0，在进行稀疏化训练时，测试验证集得到的map在0.95左右
> ![results](https://user-images.githubusercontent.com/41265163/107172691-f94c3f00-6a00-11eb-975b-7c2c0b6281a6.png)
> 请问为什么map的值会这么奇怪

需要模型足够稀疏，剪枝后map才不会降太多

**Comment by yao-zheng-yi** [comment]
> > 教一下如何得到权重图？
> 
> 用tensorboard打开看

感谢帮助，这是权重图
![Snipaste_2021-02-08_14-01-36](https://user-images.githubusercontent.com/41265163/107181730-6cac7b80-6a16-11eb-898d-28ed112949ce.png)
![Snipaste_2021-02-08_14-01-55](https://user-images.githubusercontent.com/41265163/107181756-79c96a80-6a16-11eb-9062-a98387f69f7f.png)
如何判断模型是否足够稀疏？是权重图靠近y轴吗

**Comment by ZJU-lishuang** [comment]
[案例](https://github.com/tanluren/yolov3-channel-and-layer-pruning#%E6%A1%88%E4%BE%8B)
这个模型没有稀疏好

**Comment by yao-zheng-yi** [comment]
感谢回复，请教一下权重图的纵轴代表epoch，横轴代表什么呢？
还有就是如何判断自己的模型是否稀疏好？

**Comment by yao-zheng-yi** [comment]
@ZJU-lishuang 你好，我用ZJU-lishuang/yolov5中的test.py对稀疏化训练得到的pt模型进行了测试，mAP有0.99
![Snipaste_2021-02-09_17-32-03](https://user-images.githubusercontent.com/41265163/107344061-fdf61d80-6afc-11eb-8fb5-f83ec0776b62.png)
但是使用slim_prune_yolov5s_8x.py进行8倍通道剪枝，global_percent=0.1， layer_keep=0.01，before的mAP只有0.16
![Snipaste_2021-02-09_17-32-24](https://user-images.githubusercontent.com/41265163/107344461-7361ee00-6afd-11eb-8e62-583d417a7d92.png)
想请教一下，用同一个模型文件进行测试，为什么得到的mAP会相差这么多？

**Comment by ZJU-lishuang** [comment]
@yao-zheng-yi 这是模型加载或者测试不对吧。
before的map和训练时候测试集的map相等。
信息太少不能判断问题出在哪里

**Comment by yao-zheng-yi** [comment]
我发现在进行稀疏训练的时候precision，recall和mAP这些指标的波动幅度很大，经常会掉到0，和作者给出的稀疏训练示例中的情况大不相同
这是我的可视化结果
![results](https://user-images.githubusercontent.com/41265163/107734670-f15e0900-6d38-11eb-8460-a9697b057d51.png)

这是作者稀疏训练示例的可视化结果
![Snipaste_2021-02-12_13-50-58](https://user-images.githubusercontent.com/41265163/107735146-025b4a00-6d3a-11eb-9e68-8bb2647a89d9.png)

我设置的稀疏训练的稀疏度s=0.015，这是稀疏训练的权重图，看起来应该是稀疏好了

![Snipaste_2021-02-12_13-46-03](https://user-images.githubusercontent.com/41265163/107734772-25d1c500-6d39-11eb-832a-07d1f5835905.png)

我看作者的稀疏训练示例中，mAP等指标最终都会收敛，想请教一下为什么mAP那些指标的波动情况会那么奇怪

**Comment by yao-zheng-yi** [comment]
@ZJU-lishuang 你好，请教一个问题
我在step3进行剪枝的时候，除了readme里的剪枝策略一，其他剪枝方法都有使用过，我最开始使用八倍通道剪枝，运行slim_prune_yolov5s_8x.py，进行微调之后，模型的大小减少了，但推理时间并没有减少，甚至比没有剪枝的模型还要慢上一点点。之后我尝试了除了策略一的所有剪枝方案对稀疏化训练后得到的模型进行剪枝，但剪枝后的模型只是参数量有减少，而推理时间几乎没变化，想请教一下是什么原因。
是我稀疏化训练有问题？还是剪枝策略有问题？

下面是step2稀疏化训练的可视化结果

![map](https://user-images.githubusercontent.com/41265163/109417650-76b31000-79ff-11eb-8137-e5238e2b7f23.png)
![bn](https://user-images.githubusercontent.com/41265163/109417656-7d418780-79ff-11eb-9288-4fab19dde1b5.png)


下面是我尝试的每一种剪枝策略的运行结果和参数设置

剪枝策略三，八倍通道剪枝，运行slim_prune_yolov5s_8x.py

![slim_8x_opt](https://user-images.githubusercontent.com/41265163/109417722-c42f7d00-79ff-11eb-884c-a7ff7b8275ed.png)
![slim_8x](https://user-images.githubusercontent.com/41265163/109417725-ca255e00-79ff-11eb-9b87-5161d83c86f5.png)

剪枝策略三，运行slim_prune_yolov5s.py

![slim_opt](https://user-images.githubusercontent.com/41265163/109417753-e1fce200-79ff-11eb-894a-4aebab70d9f7.png)
![slim](https://user-images.githubusercontent.com/41265163/109417761-e88b5980-79ff-11eb-81c8-c6e88437d00a.png)

剪枝策略四，层剪枝，运行layer_prune_yolov5s.py

![layer_opt](https://user-images.githubusercontent.com/41265163/109417797-0ce73600-7a00-11eb-8714-4639a61ec43e.png)
![layer](https://user-images.githubusercontent.com/41265163/109417801-12448080-7a00-11eb-8037-7bb9c41548f2.png)

剪枝策略二，对shortcut层也进行剪枝，运行shortcut_prune_yolov5s.py 

![shortut_opt](https://user-images.githubusercontent.com/41265163/109417827-2f794f00-7a00-11eb-9206-5593151aba85.png)
![shortut](https://user-images.githubusercontent.com/41265163/109417832-343e0300-7a00-11eb-8051-14d9b2bcc623.png)

**Comment by qianyuqianxun-DeepLearning** [comment]
> 你好 我尝试使用自己的数据集训练模型，按照readme的流程，在使用8倍通道剪枝的时候出现了问题。 Traceback (most recent call last): File "slim_prune_yolov5s_8x.py", line 342, in copy_weight_v4(modelyolov5, model) File "slim_prune_yolov5s_8x.py", line 23, in copy_weight_v4 copy_conv(cspnet1.cv2, model.module_list[3]) File "slim_prune_yolov5s_8x.py", line 13, in copy_conv conv_dst[0] = conv_src.conv File "/home/cwy/.conda/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in **getattr** raise ModuleAttributeError("'{}' object has no attribute '{}'".format( torch.nn.modules.module.ModuleAttributeError: 'Conv2d' object has no attribute 'conv'
> 
> 其中，cfg文件我是复制yolov5s_hand.cfg，修改了class，filters和anchors三个参数 data文件的内容如下： classes= 10 train = /data/cwy/CardNumber/yolov5_random/train.txt valid = /data/cwy/CardNumber/yolov5_random/test.txt names = data/CardNumber.names backup = /data/cwy/CardNumber/yolov5_random/
> 
> 改了很久也没能改对，请问这个问题该如何解决

您好，请问这个bug最后什么原因，试了好几个torch的版本，都不行
