### ISSUE TITLE
靓仔 你的这个项目可以之间剪枝用原版yolov5训练出来的模型吗？有哪些需要改的地方，小白请教一下

### ISSUE THREAD

**Issue by 007ARSENALZHQ** [ZJU-lishuang/yolov5_prune#15]

**Comment by ZJU-lishuang** [comment]
这个剪枝就是对接原版yolov5的模型。
你可以先跟着示例跑一遍，再看看哪里有问题。

**Comment by 007ARSENALZHQ** [comment]
> 这个剪枝就是对接原版yolov5的模型。
> 你可以先跟着示例跑一遍，再看看哪里有问题。
![2021-02-27 19-55-53 的屏幕截图](https://user-images.githubusercontent.com/66318549/109386560-6a16b500-7936-11eb-868d-74a8bf8d62c5.png)
![2021-02-27 19-56-03 的屏幕截图](https://user-images.githubusercontent.com/66318549/109386563-6be07880-7936-11eb-86f5-1e907e515a3f.png)
![2021-02-27 19-56-11 的屏幕截图](https://user-images.githubusercontent.com/66318549/109386564-6c790f00-7936-11eb-8e37-c1b0947d1bf0.png)
![results](https://user-images.githubusercontent.com/66318549/109386596-95999f80-7936-11eb-8801-35e35d382205.png)
大哥您好 我按v3的代码进行了稀疏训练发现效果相差太多想请教要如何解决 我用的s=0.001 除了img480 batch4之外其他参数没有变 不胜感激

**Comment by 007ARSENALZHQ** [comment]
大哥您好我按v3的代码进行稀疏训练发现效果相差太多想请教要如何解决
我用的s = 0.001除了img480 batch4以外其他参数没有变不胜感激
![results](https://user-images.githubusercontent.com/66318549/109386741-cfb77100-7937-11eb-9bee-c7768c3f7bf4.png)
![2021-02-27 19-55-53 的屏幕截图](https://user-images.githubusercontent.com/66318549/109386746-d3e38e80-7937-11eb-8181-6cc18e2c4cea.png)
![2021-02-27 19-56-03 的屏幕截图](https://user-images.githubusercontent.com/66318549/109386748-d47c2500-7937-11eb-92d5-ee101b1756f9.png)
![2021-02-27 19-56-11 的屏幕截图](https://user-images.githubusercontent.com/66318549/109386749-d514bb80-7937-11eb-8ddc-fe2502d02786.png)
