### ISSUE TITLE
keyerror

### ISSUE THREAD

**Issue by lccui** [ZJU-lishuang/yolov5_prune#19]
<img width="527" alt="微信图片" src="https://user-images.githubusercontent.com/44687761/111015895-e523a500-83e5-11eb-9246-db896b9f53fe.png">

**Comment by lccui** [comment]
prune_utils.py
get_input_mask(module_defs, idx, CBLidx2mask)
elif len(route_in_idxs) == 4:
    #spp结构中最后一个route
    # mask = CBLidx2mask[route_in_idxs[-1]]
    mask = CBLidx2mask[route_in_idxs[0]]
    return np.concatenate([mask, mask, mask, mask])

**Comment by lccui** [comment]
prune_utils.py
`        get_input_mask(module_defs, idx, CBLidx2mask)
elif len(route_in_idxs) == 4:
            #spp结构中最后一个route
            # mask = CBLidx2mask[route_in_idxs[-1]]
            mask = CBLidx2mask[route_in_idxs[0]]
            return np.concatenate([mask, mask, mask, mask])`

**Comment by lccui** [comment]
> get_input_mask(module_defs, idx, CBLidx2mask)

**Comment by ZJU-lishuang** [comment]
没看出来什么问题，你这问题怎么复现
keyerror盲猜一下是route_in_idxs键值不对
