### ISSUE TITLE
在剪枝的时候报错

### ISSUE THREAD

**Issue by dada1437903138** [ZJU-lishuang/yolov5_prune#27]
你好，我基于u版的yolo v5s训练出了自己的模型，用你的代码进行了稀疏训练。在使用剪枝策略1时代码报错了，信息如下：

`(pytorch) D:\CNN\yolov5\zju_prune\yolov5_prune-4>python prune_yolov5s.py --cfg D:\CNN\yolov5\yolov5\models\yolov5s.yaml --data D:\CNN\yolov5\zju_prune\yolov5_prune-4\datasets_3_aug_yolo\data.yaml --weights D:\CNN\yolov5\zju_prune\yolov5-v4-main\runs\train\s_sparsity\weights\best.pt --percent 0.8
Namespace(cfg='D:\\CNN\\yolov5\\yolov5\\models\\yolov5s.yaml', data='D:\\CNN\\yolov5\\zju_prune\\yolov5_prune-4\\datasets_3_aug_yolo\\data.yaml', img_size=416, percent=0.8, weights='D:\\CNN\\yolov5\\zju_prune\\yolov5-v4-main\\runs\\train\\s_sparsity\\weights\\best.pt')
Traceback (most recent call last):
  File "prune_yolov5s.py", line 338, in <module>
    model = Darknet(opt.cfg, (img_size, img_size)).to(device)
  File "D:\CNN\yolov5\zju_prune\yolov5_prune-4\modelsori.py", line 254, in __init__
    self.module_defs = parse_model_cfg(cfg)
  File "D:\CNN\yolov5\zju_prune\yolov5_prune-4\utils\parse_config.py", line 18, in parse_model_cfg
    key, val = line.split("=")
ValueError: not enough values to unpack (expected 2, got 1)`

我看你使用了data data/fangweisui.data这个文件作为训练数据设置，我不知道你的.data文件格式是怎样的。我使用的是yaml文件，会不会是这里有影响呢？

**Comment by dada1437903138** [comment]
我的cfg好像没设置对，按照你的训练指令设置cfg路径后还是报错。。。

**Comment by ZJU-lishuang** [comment]
python prune_yolov5s.py --cfg cfg/yolov5s_v4_hand.cfg --data data/oxfordhand.data --weights weights/last_v4s.pt --percent 0.8 --img_size 640

**Comment by ZJU-lishuang** [comment]
剪枝时的框架是darknet，yaml文件导入数据是yolov5，这两个不一样

**Comment by dada1437903138** [comment]
你好，我把cfg文件已经改过来了，但是--data xxxxxx.data 文件的格式我不知道，我用的u版yolov5中数据集的data.yaml代替的，是这里有问题吗

**Comment by dada1437903138** [comment]
请问这个.data文件如何设置呢

**Comment by ZJU-lishuang** [comment]
参考https://github.com/AlexeyAB/darknet 中的data文件设置

**Comment by dada1437903138** [comment]
> 参考https://github.com/AlexeyAB/darknet 中的data文件设置

好的谢谢
