### ISSUE TITLE
 how do u get yolov5s_v3.cfg?

### ISSUE THREAD

**Issue by codylcs** [ZJU-lishuang/yolov5_prune#3]
thanks for your works, it is wonderful,but May i know how do u get  yolov5s.cfg from yaml and .pt? if  i want prune yolov5x.pt,what should i do?  forward your reply

**Comment by ZJU-lishuang** [comment]
you should convert yaml to cfg.I rebuild the network layer by layer.

**Comment by codylcs** [comment]
sorry, i thought u convert by third-part tools,anyway,thanks for your reply
