### ISSUE TITLE
剪枝后速度的提升可以请教一下吗？

### ISSUE THREAD

**Issue by TongShuo-Demon** [ZJU-lishuang/yolov5_prune#30]
您好！请问一下剪枝后的速度提升有多少呢？

**Comment by ZJU-lishuang** [comment]
https://github.com/ZJU-lishuang/yolov5_prune/blob/v4/tk1_time.xls

**Comment by ZJU-lishuang** [comment]
有例子，可以在自己的硬件上试一下
