### ISSUE TITLE
剪枝后的模型如何做加速呢？

### ISSUE THREAD

**Issue by aa12356jm** [ZJU-lishuang/yolov5_prune#34]
请教一下作者，现在剪枝有结构化剪枝和非结构化剪枝，应该只有结构化剪枝才能实现加速，非结构化剪枝需要硬件的支持，你这里使用的是结构化剪枝吗？结构化剪枝后的模型有把权重为0的filter删除掉吗？ 谢谢

**Comment by ZJU-lishuang** [comment]
结构化剪枝，去掉了权重为0的地方，会生成新的cfg文件，也就是一个新的剪枝后的网络
