### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by aa12356jm** [ZJU-lishuang/yolov5_prune#35]
你好，请问一下这个基础训练中的 data/coco_hand.yaml在哪里呢？我下载了这个数据集发现并不是coco格式的标注格式，想跑起来整个流程还是挺麻烦的，谢谢

**Comment by ZJU-lishuang** [comment]
https://github.com/tanluren/yolov3-channel-and-layer-pruning#%E6%A1%88%E4%BE%8B
