### ISSUE TITLE
请教关于剪枝后map为0的问题

### ISSUE THREAD

**Issue by mengqingyan97** [ZJU-lishuang/yolov5_prune#37]
当我使用自己的数据集进行训练时，基础训练过程和稀疏训练过程均正常，但是进行到剪枝的时候，P，R，map，F1的值均变成0；
我想请教您这个问题需要如何解决？
我的数据集一共2059张图片，做火灾识别，classes=1
![image](https://user-images.githubusercontent.com/74995411/120327825-c36af780-c31c-11eb-9388-cb9b7989e706.png)

**Comment by ZJU-lishuang** [comment]
降低剪枝率看看剪枝后模型map是否能提升。
这个情况一般是模型稀疏度不够导致的。

**Comment by mengqingyan97** [comment]
还有一个问题，当我进行剪枝的时候，剪枝前后的map值急剧下降；
我稀疏训练得到的map值是0.73，进行到剪枝第一步的时候，let's test the original model first:   map直接降到0.25，剪枝后变为0
请问这种情况也是因为稀疏训练不够导致的吗？我基础训练和稀疏训练都是100epoch。
![image](https://user-images.githubusercontent.com/74995411/120412029-63aa3600-c388-11eb-93a3-1c74042fd1ac.png)

**Comment by ZJU-lishuang** [comment]
稀疏度不是看map的
是看[这里](https://github.com/ZJU-lishuang/yolov5-v4/blob/main/train_sparsity.py#L504)记录的东西

**Comment by mengqingyan97** [comment]
![Uploading QQ图片20210603192426.png…]()

**Comment by rachel-chennn** [comment]
> 

您好，我遇到了跟您一样的问题，稀疏后剪枝mAP就变小了，请问是通过重新稀疏训练解决的嘛？
