### ISSUE TITLE
map before prune?

### ISSUE THREAD

**Issue by codylcs** [ZJU-lishuang/yolov5_prune#4]
command:
python prune_yolov5s.py --cfg cfg/yolov5s.cfg --data data/fangweisui.data --weights weights/yolov5s_prune0.pt --percent 0.8
code used:
[https://github.com/ZJU-lishuang/yolov5]

question:
+------------+----------+----------+
| Metric     | Before   | After    |
+------------+----------+----------+
| mAP        | 0.025648 | 0.000000 |
| Parameters | 7263185  | 1790052  |
| Inference  | 0.0165   | 0.0172   |
+------------+----------+----------+
so when eval the ori model,what is the format of annos ?like normalized [classid,x_center,y_center,w,h] or coco format?

**Comment by ZJU-lishuang** [comment]
I don't find prune_yolov5s.py in [yolov5](https://github.com/ZJU-lishuang/yolov5).
the format of annos is yolo format.[class x_center y_center width height]
you can refer to [Train-Custom-Data](https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data)

**Comment by codylcs** [comment]
model is trained from [https://github.com/ZJU-lishuang/yolov5](**url**) ,prune code from [https://github.com/ZJU-lishuang/yolov5_prune](url),and my data format has been made like[2.000000 0.190911 0.586809 0.173847 0.043580],i just make sure eval data u used

**Comment by codylcs** [comment]
one epoch as flow,there is nothing wrong:
Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
     16/49     4.72G   0.05814   0.01787   0.01538    0.0914        22       640: 100%|██████████| 136/136 [02:52<00:00,  1.27s/it]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 34/34 [00:06<00:00,  5.33it/s]
                 all         543         798       0.348       0.845       0.695       0.273
,but when eval the data,it was weird

**Comment by ZJU-lishuang** [comment]
before prune model ,sparse training should be performed on the model.
Or you can set the percent to 1 to check it.
You also can refer the test_yolov5s.py to see the result in the images.

**Comment by codylcs** [comment]
> 训练模型所用脚本/yolov5_v2/train_pytorch1.4.py，训练过程正常
> 用进行/yolov5_v2/detect.py测试，预测结果正常
> yolov5_prune/cfg/yolov5s.cfg 修改class=4,filers=27 ,27 = (4+5）*3
> yolov5_prune/cfg/yolov5s.yaml 修改类别 nc=4
> lcs.data 

```
classes=4
train=/home/cody/PycharmProjects/darknet/build/darknet/x64/data/train.txt
valid=/home/cody/PycharmProjects/darknet/build/darknet/x64/data/test.txt
names=/home/cody/PycharmProjects/darknet/build/darknet/x64/data/t.names
backup=backup/
eval=coco
```

> yolov5_prune.py

```
img_size = opt.img_size
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = Darknet('cfg/yolov5s.cfg', (img_size, img_size)).to(device)
modelyolov5 = Model('cfg/yolov5s.yaml', nc=4).to(device)
modelyolov5=torch.load('weights/best.pt', map_location=device)['model'].float()  # load FP32 model
copy_weight(modelyolov5, model)
```
yolov5_prune output as flow:
```
Namespace(cfg='cfg/yolov5s.cfg', data='data/lcs.data', img_size=512, percent=0.8, weights='weights/yolov5s.pt')

                 from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Focus                     [3, 32, 3]                    
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     19904  models.common.BottleneckCSP             [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  1    161152  models.common.BottleneckCSP             [128, 128, 3]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  1    641792  models.common.BottleneckCSP             [256, 256, 3]                 
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]        
  9                -1  1   1248768  models.common.BottleneckCSP             [512, 512, 1, False]          
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1    378624  models.common.BottleneckCSP             [512, 256, 1, False]          
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1     95104  models.common.BottleneckCSP             [256, 128, 1, False]          
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1    313088  models.common.BottleneckCSP             [256, 256, 1, False]          
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   1248768  models.common.BottleneckCSP             [512, 512, 1, False]          
 24      [17, 20, 23]  1     24273  models.yolo.Detect                      [4, [[40, 39, 51, 50, 61, 59], [75, 69, 62, 92, 88, 98], [115, 77, 93, 129, 128, 115]], [128, 256, 512]]
Model Summary: 191 layers, 7.26318e+06 parameters, 7.26318e+06 gradients


let's test the original model first:
               Class    Images   Targets         P         R       mAP        F1:   0%|          | 0/34 [00:00<?, ?it/s]/home/cody/PycharmProjects/yolov5_prune/test.py:248: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629395347/work/torch/csrc/utils/python_arg_parser.cpp:766.)
  m = (pcls == tcls_tensor).nonzero().view(-1)
               Class    Images   Targets         P         R       mAP        F1: 100%|██████████| 34/34 [00:16<00:00,  2.07it/s]
                 all       543       769   0.00814     0.737      0.12    0.0161
Suggested Gamma threshold should be less than 1.0039.
The corresponding prune ratio is 0.033, but you can set higher.
the required prune percent is 0.8
Gamma value that less than 1.0020 are set to zero!
let's test the current model!
               Class    Images   Targets         P         R       mAP        F1: 100%|██████████| 34/34 [00:08<00:00,  4.11it/s]
                 all       543       769         0         0         0         0
Number of channels has been reduced from 5312 to 1395
Prune ratio: 0.737
mAP of the 'pruned' model is 0.0000
layer index:   1 	 total channel:   32 	 remaining channel:   15
layer index:   6 	 total channel:   32 	 remaining channel:   14
layer index:  12 	 total channel:   64 	 remaining channel:   24
layer index:  17 	 total channel:   64 	 remaining channel:   25
layer index:  20 	 total channel:   64 	 remaining channel:   22
layer index:  23 	 total channel:   64 	 remaining channel:   20
layer index:  29 	 total channel:  128 	 remaining channel:   51
layer index:  34 	 total channel:  128 	 remaining channel:   41
layer index:  37 	 total channel:  128 	 remaining channel:   40
layer index:  40 	 total channel:  128 	 remaining channel:   39
layer index:  46 	 total channel:  256 	 remaining channel:  124
layer index:  47 	 total channel:  512 	 remaining channel:  100
layer index:  58 	 total channel:  256 	 remaining channel:   45
layer index:  59 	 total channel:  256 	 remaining channel:   42
layer index:  64 	 total channel:  512 	 remaining channel:   94
layer index:  70 	 total channel:  128 	 remaining channel:   34
layer index:  71 	 total channel:  128 	 remaining channel:   39
layer index:  76 	 total channel:  256 	 remaining channel:   71
layer index:  82 	 total channel:   64 	 remaining channel:   24
layer index:  83 	 total channel:   64 	 remaining channel:   23
layer index:  88 	 total channel:  128 	 remaining channel:   53
layer index:  92 	 total channel:  128 	 remaining channel:   64
layer index:  96 	 total channel:  128 	 remaining channel:   39
layer index:  97 	 total channel:  128 	 remaining channel:   36
layer index: 102 	 total channel:  256 	 remaining channel:   70
layer index: 106 	 total channel:  256 	 remaining channel:  115
layer index: 110 	 total channel:  256 	 remaining channel:   42
layer index: 111 	 total channel:  256 	 remaining channel:   44
layer index: 116 	 total channel:  512 	 remaining channel:   45
Prune channels: 3917	Prune ratio: 0.366

now prune the model but keep size,(actually add offset of BN beta to next layer), let's see how the mAP goes
               Class    Images   Targets         P         R       mAP        F1: 100%|██████████| 34/34 [00:07<00:00,  4.30it/s]
                 all       543       769         0         0         0         0

testing avg forward time...
testing the mAP of final pruned model
               Class    Images   Targets         P         R       mAP        F1: 100%|██████████| 34/34 [00:07<00:00,  4.33it/s]
                 all       543       769         0         0         0         0
+------------+----------+----------+
| Metric     | Before   | After    |
+------------+----------+----------+
| mAP        | 0.119604 | 0.000000 |
| Parameters | 7263185  | 2279995  |
| Inference  | 0.0169   | 0.0159   |
+------------+----------+----------+
Config file has been saved: cfg/prune_0.8_yolov5s.cfg
Compact model has been saved: weights/prune_0.8_yolov5s.weights
```
could u find something wrong? thanks

**Comment by ZJU-lishuang** [comment]
调高剪枝率percent到1看看map是不是一样的

**Comment by codylcs** [comment]
调高剪枝率percent到1后输出
`let's test the original model first:
               Class    Images   Targets         P         R       mAP        F1:   0%|          | 0/34 [00:00<?, ?it/s]/home/cody/PycharmProjects/yolov5_prune/test.py:248: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629395347/work/torch/csrc/utils/python_arg_parser.cpp:766.)
  m = (pcls == tcls_tensor).nonzero().view(-1)
               Class    Images   Targets         P         R       mAP        F1: 100%|██████████| 34/34 [00:16<00:00,  2.02it/s]
                 all       543       769   0.00814     0.737      0.12    0.0161
Suggested Gamma threshold should be less than 1.0039.
The corresponding prune ratio is 0.033, but you can set higher.
the required prune percent is 1
Traceback (most recent call last):
  File "/home/cody/PycharmProjects/yolov5_prune/prune_yolov5s.py", line 324, in <module>
    threshold = prune_and_eval(model, sorted_bn, percent)
  File "/home/cody/PycharmProjects/yolov5_prune/prune_yolov5s.py", line 299, in prune_and_eval
    thre = sorted_bn[thre_index]
IndexError: index 5312 is out of bounds for dimension 0 with size 5312

Process finished with exit code 1
`

**Comment by ZJU-lishuang** [comment]
设成0.9看看吧，这是索引越界了

**Comment by codylcs** [comment]
改动 thre = sorted_bn[thre_index-1]，消除错误后输出
```
let's test the original model first:
               Class    Images   Targets         P         R       mAP        F1:   0%|          | 0/34 [00:00<?, ?it/s]/home/cody/PycharmProjects/yolov5_prune/test.py:248: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629395347/work/torch/csrc/utils/python_arg_parser.cpp:766.)
  m = (pcls == tcls_tensor).nonzero().view(-1)
               Class    Images   Targets         P         R       mAP        F1: 100%|██████████| 34/34 [00:16<00:00,  2.12it/s]
                 all       543       769   0.00814     0.737      0.12    0.0161
Suggested Gamma threshold should be less than 1.0039.
The corresponding prune ratio is 0.033, but you can set higher.
the required prune percent is 1
Gamma value that less than 1.1523 are set to zero!
let's test the current model!
               Class    Images   Targets         P         R       mAP        F1: 100%|██████████| 34/34 [00:38<00:00,  1.14s/it]
                 all       543       769  0.000166    0.0451  3.27e-05  0.000331
Number of channels has been reduced from 5312 to 1
Prune ratio: 1.000
mAP of the 'pruned' model is 0.0000
layer index:   1 	 total channel:   32 	 remaining channel:    1
layer index:   6 	 total channel:   32 	 remaining channel:    1
layer index:  12 	 total channel:   64 	 remaining channel:    1
layer index:  17 	 total channel:   64 	 remaining channel:    1
layer index:  20 	 total channel:   64 	 remaining channel:    1
layer index:  23 	 total channel:   64 	 remaining channel:    1
layer index:  29 	 total channel:  128 	 remaining channel:    1
layer index:  34 	 total channel:  128 	 remaining channel:    1
layer index:  37 	 total channel:  128 	 remaining channel:    1
layer index:  40 	 total channel:  128 	 remaining channel:    2
layer index:  46 	 total channel:  256 	 remaining channel:    1
layer index:  47 	 total channel:  512 	 remaining channel:    1
layer index:  58 	 total channel:  256 	 remaining channel:    1
layer index:  59 	 total channel:  256 	 remaining channel:    5
layer index:  64 	 total channel:  512 	 remaining channel:    2
layer index:  70 	 total channel:  128 	 remaining channel:    1
layer index:  71 	 total channel:  128 	 remaining channel:    1
layer index:  76 	 total channel:  256 	 remaining channel:    1
layer index:  82 	 total channel:   64 	 remaining channel:    1
layer index:  83 	 total channel:   64 	 remaining channel:    1
layer index:  88 	 total channel:  128 	 remaining channel:    1
layer index:  92 	 total channel:  128 	 remaining channel:    1
layer index:  96 	 total channel:  128 	 remaining channel:    1
layer index:  97 	 total channel:  128 	 remaining channel:    1
layer index: 102 	 total channel:  256 	 remaining channel:    3
layer index: 106 	 total channel:  256 	 remaining channel:    1
layer index: 110 	 total channel:  256 	 remaining channel:    3
layer index: 111 	 total channel:  256 	 remaining channel:    3
layer index: 116 	 total channel:  512 	 remaining channel:    1
Prune channels: 10551	Prune ratio: 0.987

now prune the model but keep size,(actually add offset of BN beta to next layer), let's see how the mAP goes
               Class    Images   Targets         P         R       mAP        F1: 100%|██████████| 34/34 [00:45<00:00,  1.34s/it]
                 all       543       769  0.000163    0.0443  4.29e-05  0.000325

testing avg forward time...
testing the mAP of final pruned model
               Class    Images   Targets         P         R       mAP        F1: 100%|██████████| 34/34 [00:42<00:00,  1.26s/it]
                 all       543       769  0.000163    0.0443  4.33e-05  0.000325
+------------+----------+----------+
| Metric     | Before   | After    |
+------------+----------+----------+
| mAP        | 0.119604 | 0.000043 |
| Parameters | 7263185  | 1104014  |
| Inference  | 0.0198   | 0.0199   |
+------------+----------+----------+
Config file has been saved: cfg/prune_1_yolov5s.cfg
Compact model has been saved: weights/prune_1_yolov5s.weights

Process finished with exit code 0

```

**Comment by ZJU-lishuang** [comment]
你这remaining channel留下的通道都快没了:sweat_smile:
看起来是没有稀疏训练，所以剪枝效果不好

**Comment by ZJU-lishuang** [comment]
调高剪枝率percent到0.9或0.99看看，我当时也是没稀疏训练直接剪枝，map也这样不给面子，我还以为坏掉了

**Comment by codylcs** [comment]
稀疏那个操作我后面可以改，应该稀疏不到位，但是剪枝之前的map不正常阿

**Comment by codylcs** [comment]
/home/cody/PycharmProjects/yolov5_v2/train_pytorch1.4.py 是将训练和稀疏分开作了，才看到，还以为一边训练一边稀疏呢，剪枝后的map为0那就符合你说的 了

**Comment by ZJU-lishuang** [comment]
没，是先正常训练一遍，再稀疏训练一遍，再剪枝

**Comment by codylcs** [comment]
那我就等模型完全收敛，再验证下，刚才是取train_pytorch1.4.py中间的模型结果去/yolov5_prune/prune_yolov5s.py 作的剪枝，整个脚本看的有点糊涂了，不好意思哈

**Comment by codylcs** [comment]
为什么train_pytorch1.4.py训练的模型大小是58.5M 而不是14.7M?

**Comment by ZJU-lishuang** [comment]
首先是中间模型没有除去多余的参数，其次保存的是float32，最后才保存float16.

教程最近没什么空去写，就一直拖着了:joy:

**Comment by codylcs** [comment]
恩，明白了，方便说下哪个脚本是测试剪枝后的模型吗？单张图像的

**Comment by ZJU-lishuang** [comment]
我刚才说的[test_yolov5s.py](https://github.com/ZJU-lishuang/yolov5_prune/blob/main/test_yolov5s.py)
这个是单张测试的，我用来对比剪枝前和剪枝后的效果

**Comment by ZJU-lishuang** [comment]
你可以根据自己需要改一下

**Comment by codylcs** [comment]
谢谢你的贡献，这个工程如果加以整理的话，星星破万不在话下

**Comment by codylcs** [comment]
训练最后一个epoch: 

Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
     49/49     4.72G   0.04468   0.01459  0.009728     0.069        30       640: 100%|██████████| 136/136 [01:28<00:00,  1.54it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 34/34 [00:03<00:00, 10.32it/s]
                 all         543         798       0.608       0.958       0.898       0.485

yolov5_prune.py prune之前的结果

Class    Images   Targets         P         R       mAP        F1: 100%|██████████| 34/34 [00:05<00:00,  6.37it/s]
                 all       543       769    0.0289     0.777     0.162    0.0555

结果出入比较大阿？

**Comment by ZJU-lishuang** [comment]
可能测试代码不一样吧，测试map时用的test.py ，这个是yolov3那里过来的，和yolov5不一样，我没做这里的代码对齐。

**Comment by codylcs** [comment]
prune依赖于这个map吗？还是说两者是解耦的？

**Comment by ZJU-lishuang** [comment]
map是测试用的吧，可以用原来项目中的测试代码，这个和剪枝没关系，map只是看模型性能。

**Comment by codylcs** [comment]
好的，明后天我再琢磨下，辛苦了

**Comment by eeric** [comment]
The author needs to sort out the pruning code tutorial

**Comment by codylcs** [comment]
script test_yolov5s has been testes before,the result is normal,but after pruned,output was none,so why?

**Comment by codylcs** [comment]
Class    Images   Targets         P                R           mAP        F1: 100%|██████████| 34/34 [00:10<00:00,  3.26it/s]
 all        543           769                0.0232      0.85     0.236     0.045
 the results show that  recall is 0.85 but precise is 0.023,anyone can give some advices？

**Comment by seeyouagain111** [comment]
> Class Images Targets P R mAP F1: 100%|██████████| 34/34 [00:10<00:00, 3.26it/s]
> all 543 769 0.0232 0.85 0.236 0.045
> the results show that recall is 0.85 but precise is 0.023,anyone can give some advices？

because in test，con_thref is 0.001 ,you can set it  to be 0.4

**Comment by codylcs** [comment]
> > Class Images Targets P R mAP F1: 100%|██████████| 34/34 [00:10<00:00, 3.26it/s]
> > all 543 769 0.0232 0.85 0.236 0.045
> > the results show that recall is 0.85 but precise is 0.023,anyone can give some advices？
> 
> because in test，con_thref is 0.001 ,you can set it to be 0.4

after modified con_thref 0.001 ->0.4,it works, the result as flowing:
`+------------+----------+----------+
| Metric     | Before   | After    |
+------------+----------+----------+
| mAP        | 0.197590 | 0.120179 |
| Parameters | 7263185  | 1887653  |
| Inference  | 0.0069   | 0.0068   |`
but p and R far below the value when training, could u show some advices?

**Comment by seeyouagain111** [comment]
> > > Class Images Targets P R mAP F1: 100%|██████████| 34/34 [00:10<00:00, 3.26it/s]
> > > all 543 769 0.0232 0.85 0.236 0.045
> > > the results show that recall is 0.85 but precise is 0.023,anyone can give some advices？
> > 
> > 
> > because in test，con_thref is 0.001 ,you can set it to be 0.4
> 
> after modified con_thref 0.001 ->0.4,it works, the result as flowing:
> +------------+----------+----------+
> | Metric | Before | After |
> +------------+----------+----------+
> | mAP | 0.197590 | 0.120179 |
> | Parameters | 7263185 | 1887653 |
> | Inference | 0.0069 | 0.0068 |
> but p and R far below the value when training, could u show some advices?

我和你一样的问题，剪枝完以后mAP就降为0了，我怀疑是稀疏度不够的原因，正在重新做稀疏训练

**Comment by ZJU-lishuang** [comment]
剪枝前要用tenserboard看一下稀疏训练的bn_weight的效果，如果稀疏度不够，后面剪枝会乱剪，造成map为0。
稀疏训练调参的话，批处理大小batchsize，稀疏度s，迭代次数epoch这三个改动有影响。

**Comment by ZJU-lishuang** [comment]
更新了readme，添加了可复现的流程，可以参考看一下。
