### ISSUE TITLE
你好，我在自己的yolo5s工程中使用你的剪枝脚本，为什么mAP测试结果都是0

### ISSUE THREAD

**Issue by seeyouagain111** [ZJU-lishuang/yolov5_prune#5]
我在yolov5s源码里训练了一个classes=1的模型。训练过程没有转darknet模式。然后用你的剪枝脚本剪枝。测试效果显示转darknet成功了，但是测试将多余层参数置零时的mAP都为0

**Comment by ZJU-lishuang** [comment]
我这个不转darknet，还是使用yolov5工程训练测试.
mAP为0这个问题，我准备有空的时候基于官方的模型进行剪枝，推出一版教程，我不能提供项目中使用的模型。目前手头没有方便公开的模型。
或者你提供剪枝前后的模型和一张测试图片，我的debug一下。

**Comment by seeyouagain111** [comment]
> 我这个不转darknet，还是使用yolov5工程训练测试.
> mAP为0这个问题，我准备有空的时候基于官方的模型进行剪枝，推出一版教程，我不能提供项目中使用的模型。目前手头没有方便公开的模型。
> 或者你提供剪枝前后的模型和一张测试图片，我的debug一下。

我现在稀疏训练用的是我自己的代码，我请问你这边稀疏训练用的是哪个脚本，我准备试下你的。我看你还有个yolov5-v3工程，那边的训练代码可以用吗

**Comment by ZJU-lishuang** [comment]
我做剪枝的时候，yolov5还没有第三版。
yolov5-v3工程是在yolov5第三版基础上加了稀疏训练的代码

**Comment by seeyouagain111** [comment]
> 我做剪枝的时候，yolov5还没有第三版。
> yolov5-v3工程是在yolov5第三版基础上加了稀疏训练的代码

先谢谢大佬。我刚看了v3里的稀疏训练代码，有不明白的地方，就是updateBN这个函数传入的是cfg_model的参数，可是训练的时候一直是用model的参数在训练，我不明白最后是怎么训练出稀疏化的参数的

**Comment by ZJU-lishuang** [comment]
[copy_weight(model, cfg_model)](https://github.com/ZJU-lishuang/yolov5-v3/blob/main/train_sparsity.py#L377)
将model的参数指向了cfg_model的参数，这两个相当于是同一个参数的不同的名字。
我debug过了，不需要注释上面那一行代码

**Comment by ZJU-lishuang** [comment]
我也是参考别人代码改的，不敢当大佬

**Comment by seeyouagain111** [comment]
> 我也是参考别人代码改的，不敢当大佬

好的多谢，建议出个详细的教程，star数能起飞

**Comment by ZJU-lishuang** [comment]
已经计划在做了

**Comment by seeyouagain111** [comment]
我发现你的稀疏化训练epoch是100.我正常训练自己的数据是11个epoch就能收敛到loss最小，那我稀疏化训练也是差不多吗，还是说也设置100好一些

**Comment by ZJU-lishuang** [comment]
我之前训练100个epoch。
稀疏训练100个epoch，稀疏度不够，剪枝率高一点，map就没了。
增加到300个epoch，感觉稀疏度满足了要求。
具体参考[tanluren/yolov3-channel-and-layer-pruning](https://github.com/tanluren/yolov3-channel-and-layer-pruning)
这个我也没做很多实验，主要看Tensorboard里面的图吧，那个图还是很好看的

**Comment by seeyouagain111** [comment]
> 我之前训练100个epoch。
> 稀疏训练100个epoch，稀疏度不够，剪枝率高一点，map就没了。
> 增加到300个epoch，感觉稀疏度满足了要求。
> 具体参考[tanluren/yolov3-channel-and-layer-pruning](https://github.com/tanluren/yolov3-channel-and-layer-pruning)
> 这个我也没做很多实验，主要看Tensorboard里面的图吧，那个图还是很好看的

稀疏训练是在之前已经在自由数据集上训练好的模型上finetune吗？还是加载官方预训练模型从头训练啊

**Comment by seeyouagain111** [comment]
你好，我按照你的代码稀疏训练，剪枝以后map还是0.我看了下我的bn weights大多集中在0.7以上。请问这么高的原因是什么

**Comment by ZJU-lishuang** [comment]
bn weights大多集中在0.7以上是什么意思？
这是我稀疏训练迭代100次的图
![image](https://user-images.githubusercontent.com/26588466/101436749-ba8b0180-3949-11eb-81d3-27f179534e67.png)
这是我稀疏训练迭代300次的图
![image](https://user-images.githubusercontent.com/26588466/101436764-beb71f00-3949-11eb-8277-72815946fd55.png)
稀疏度不够吧

**Comment by seeyouagain111** [comment]
大多集中在0.7以上就是几乎所有值都大于0.7，而你这里迭代300次以后大部分值都在0.5以下。
那么如何解决稀疏度不够呢

**Comment by ZJU-lishuang** [comment]
增加迭代次数

**Comment by seeyouagain111** [comment]
我在使用的yolo第二版里的prune_finetune.py过程中，提示'Darknet' object has no attribute 'model'。大意是原先yolov5的model是pytorch的，你这边换成darknet后无法执行一些操作了，请问你又遇到这种情况吗

**Comment by seeyouagain111** [comment]
大佬，我使用了prune_finetune.py时候，我用训练集当测试集测试了一下里面的test函数输出mAP为0，但是loss是很低的，是不是test不支持darknet结构啊，你有研究过吗

**Comment by ZJU-lishuang** [comment]
载入的模型网络结构是一样的，我在自己项目上用过。
目前在跑开源数据，准备Tutorial中

**Comment by seeyouagain111** [comment]
> 载入的模型网络结构是一样的，我在自己项目上用过。
> 目前在跑开源数据，准备Tutorial
我把你的整个yolov5 第二版工程下下来，改了路径和配置文件，跑prune_finetune.py提示'Darknet' object has no attribute 'model'

请问是什么原因

**Comment by ZJU-lishuang** [comment]
Darknet这个类没有属性model
这个我要debug看一下

**Comment by seeyouagain111** [comment]
> 这个类没有属性model
> 这个我要debug看一下
这是在check_anchors函数里报错的

**Comment by seeyouagain111** [comment]
> Darknet这个类没有属性model
> 这个我要debug看一下

还有一个问题是报错 Yololayer里不存在anchor_vec,我输出看了下好像是用anchors代替了

**Comment by ZJU-lishuang** [comment]
更新了readme，添加了可复现的流程，可以参考看一下。

修复了prune_finetune.py的问题

**Comment by seeyouagain111** [comment]
https://github.com/ZJU-lishuang/yolov5/blob/dfa8a7f1b6be19503b76b0d918deaeee8618d7ab/utils/general.py#L596

这一行提示无法找到anchor_vec ，请问你没遇到过吗

**Comment by ZJU-lishuang** [comment]
没有
你这是图片输入尺寸过小吧，[create_grids](https://github.com/ZJU-lishuang/yolov5/blob/master/modelsori.py#L174)这里生成anchor_vec，
没有生成说明不满条件
```
            if (self.nx, self.ny) != (nx, ny):
                create_grids(self, img_size, (nx, ny), p.device, p.dtype)
```
但self.nx, self.ny初始化是0

**Comment by seeyouagain111** [comment]
> 没有
> 你这是图片输入尺寸过小吧，[create_grids](https://github.com/ZJU-lishuang/yolov5/blob/master/modelsori.py#L174)这里生成anchor_vec，
> 没有生成说明不满条件
> 
> ```
>             if (self.nx, self.ny) != (nx, ny):
>                 create_grids(self, img_size, (nx, ny), p.device, p.dtype)
> ```
> 
> 但self.nx, self.ny初始化是0

不是size的问题，我用单gpu跑prune_finetune.py就不会报这个错误，多gpu就会报找不到anchor_vec，请问你测试是单gpu还是多gpu

**Comment by ZJU-lishuang** [comment]
我用的单gpu，没有多卡测试。
这应该是多gpu中只有一个有超参数，其它没有，这里没处理。
或者
```
# DP mode
    if cuda and rank == -1 and torch.cuda.device_count() > 1:
        model = torch.nn.DataParallel(model)
        model.module_list = model.module.module_list
        model.yolo_layers = model.module.yolo_layers  # move yolo layer indices to top level
```
加了参数转移
```
# DDP mode
    if cuda and rank != -1:
        model = DDP(model, device_ids=[rank], output_device=rank)
```
这里没加导致的

**Comment by seeyouagain111** [comment]
> 我用的单gpu，没有多卡测试。
> 这应该是多gpu中只有一个有超参数，其它没有，这里没处理。
> 或者
> 
> ```
> # DP mode
>     if cuda and rank == -1 and torch.cuda.device_count() > 1:
>         model = torch.nn.DataParallel(model)
>         model.module_list = model.module.module_list
>         model.yolo_layers = model.module.yolo_layers  # move yolo layer indices to top level
> ```
> 
> 加了参数转移
> 
> ```
> # DDP mode
>     if cuda and rank != -1:
>         model = DDP(model, device_ids=[rank], output_device=rank)
> ```
> 
> 这里没加导致的

这个我加了的。你方便试下多gpu训练会报错吗，如果报错的话，输出loss之前就会报错了

**Comment by dpk3** [comment]
楼主 有计划加入蒸馏吗 之前的v3的那个试了一下减值后再加蒸馏 好像很有用

**Comment by ZJU-lishuang** [comment]
直接参考那个v3在对应位置加上蒸馏代码应该就可以用了。

**Comment by ZJU-lishuang** [comment]
@seeyouagain111 多gpu训练不会报错

**Comment by DaChaoXc** [comment]
> 大多集中在0.7以上就是几乎所有值都大于0.7，而你这里迭代300次以后大部分值都在0.5以下。
> 那么如何解决稀疏度不够呢

我的做法是减小学习率和压缩率

**Comment by ZJU-lishuang** [comment]
稀疏训练调参的话，批处理大小batchsize，稀疏度s，迭代次数epoch这三个改动有影响。

**Comment by dpk3** [comment]
> > 大多集中在0.7以上就是几乎所有值都大于0.7，而你这里迭代300次以后大部分值都在0.5以下。
> > 那么如何解决稀疏度不够呢
> 
> 我的做法是减小学习率和压缩率

我尝试了不同的sr（从0.0001-0.001-0.01-1-5-10-。。。-5000）最后发现无论稀疏训练后map衰减到多少 剪枝后结果都是0，然后发现是因为我改了hyp参数的缘故，使用scratch的就没有这种问题 ，但问题是我的数据集是我自己跑的超参数，用我自己的超参数一旦剪枝就没有map了  所以不知道是不是因为你换了hyp参数导致的

**Comment by seeyouagain111** [comment]
> > > 大多集中在0.7以上就是几乎所有值都大于0.7，而你这里迭代300次以后大部分值都在0.5以下。
> > > 那么如何解决稀疏度不够呢
> > 
> > 
> > 我的做法是减小学习率和压缩率
> 
> 我尝试了不同的sr（从0.0001-0.001-0.01-1-5-10-。。。-5000）最后发现无论稀疏训练后map衰减到多少 剪枝后结果都是0，然后发现是因为我改了hyp参数的缘故，使用scratch的就没有这种问题 ，但问题是我的数据集是我自己跑的超参数，用我自己的超参数一旦剪枝就没有map了 所以不知道是不是因为你换了hyp参数导致的

我也是用scratch.yaml的超参训练，s=1000，才剪枝成功

**Comment by DaChaoXc** [comment]
> > > > 大多集中在0.7以上就是几乎所有值都大于0.7，而你这里迭代300次以后大部分值都在0.5以下。
> > > > 那么如何解决稀疏度不够呢
> > > 
> > > 
> > > 我的做法是减小学习率和压缩率
> > 
> > 
> > 我尝试了不同的sr（从0.0001-0.001-0.01-1-5-10-。。。-5000）最后发现无论稀疏训练后map衰减到多少 剪枝后结果都是0，然后发现是因为我改了hyp参数的缘故，使用scratch的就没有这种问题 ，但问题是我的数据集是我自己跑的超参数，用我自己的超参数一旦剪枝就没有map了 所以不知道是不是因为你换了hyp参数导致的
> 
> 我也是用scratch.yaml的超参训练，s=1000，才剪枝成功

稀疏scale不应该是小于1吗，类似于0.01这种，1000也可以？

**Comment by seeyouagain111** [comment]
> > > > > 大多集中在0.7以上就是几乎所有值都大于0.7，而你这里迭代300次以后大部分值都在0.5以下。
> > > > > 那么如何解决稀疏度不够呢
> > > > 
> > > > 
> > > > 我的做法是减小学习率和压缩率
> > > 
> > > 
> > > 我尝试了不同的sr（从0.0001-0.001-0.01-1-5-10-。。。-5000）最后发现无论稀疏训练后map衰减到多少 剪枝后结果都是0，然后发现是因为我改了hyp参数的缘故，使用scratch的就没有这种问题 ，但问题是我的数据集是我自己跑的超参数，用我自己的超参数一旦剪枝就没有map了 所以不知道是不是因为你换了hyp参数导致的
> > 
> > 
> > 我也是用scratch.yaml的超参训练，s=1000，才剪枝成功
> 
> 稀疏scale不应该是小于1吗，类似于0.01这种，1000也可以？

是啊，不试不知道啊

**Comment by dpk3** [comment]
> > > > > > 大多集中在0.7以上就是几乎所有值都大于0.7，而你这里迭代300次以后大部分值都在0.5以下。
> > > > > > 那么如何解决稀疏度不够呢
> > > > > 
> > > > > 
> > > > > 我的做法是减小学习率和压缩率
> > > > 
> > > > 
> > > > 我尝试了不同的sr（从0.0001-0.001-0.01-1-5-10-。。。-5000）最后发现无论稀疏训练后map衰减到多少 剪枝后结果都是0，然后发现是因为我改了hyp参数的缘故，使用scratch的就没有这种问题 ，但问题是我的数据集是我自己跑的超参数，用我自己的超参数一旦剪枝就没有map了 所以不知道是不是因为你换了hyp参数导致的
> > > 
> > > 
> > > 我也是用scratch.yaml的超参训练，s=1000，才剪枝成功
> > 
> > 
> > 稀疏scale不应该是小于1吗，类似于0.01这种，1000也可以？
> 
> 是啊，不试不知道啊

那你系数训练的时候模型性能衰减的还能接受吗我的25差不多还行  再往上加就直接没精度了

**Comment by seeyouagain111** [comment]
> > > > > > > 大多集中在0.7以上就是几乎所有值都大于0.7，而你这里迭代300次以后大部分值都在0.5以下。
> > > > > > > 那么如何解决稀疏度不够呢
> > > > > > 
> > > > > > 
> > > > > > 我的做法是减小学习率和压缩率
> > > > > 
> > > > > 
> > > > > 我尝试了不同的sr（从0.0001-0.001-0.01-1-5-10-。。。-5000）最后发现无论稀疏训练后map衰减到多少 剪枝后结果都是0，然后发现是因为我改了hyp参数的缘故，使用scratch的就没有这种问题 ，但问题是我的数据集是我自己跑的超参数，用我自己的超参数一旦剪枝就没有map了 所以不知道是不是因为你换了hyp参数导致的
> > > > 
> > > > 
> > > > 我也是用scratch.yaml的超参训练，s=1000，才剪枝成功
> > > 
> > > 
> > > 稀疏scale不应该是小于1吗，类似于0.01这种，1000也可以？
> > 
> > 
> > 是啊，不试不知道啊
> 
> 那你稀疏训练的时候模型性能衰减的还能接受吗我的25差不多还行 再往上加就直接没精度了

mAP从0.87降到了0.8，还可以接受

**Comment by dpk3** [comment]
为什么f1比较低，还是说这类任务基本只关注map就行

**Comment by dpk3** [comment]
> > > > > > > > 大多集中在0.7以上就是几乎所有值都大于0.7，而你这里迭代300次以后大部分值都在0.5以下。
> > > > > > > > 那么如何解决稀疏度不够呢
> > > > > > > 
> > > > > > > 
> > > > > > > 我的做法是减小学习率和压缩率
> > > > > > 
> > > > > > 
> > > > > > 我尝试了不同的sr（从0.0001-0.001-0.01-1-5-10-。。。-5000）最后发现无论稀疏训练后map衰减到多少 剪枝后结果都是0，然后发现是因为我改了hyp参数的缘故，使用scratch的就没有这种问题 ，但问题是我的数据集是我自己跑的超参数，用我自己的超参数一旦剪枝就没有map了 所以不知道是不是因为你换了hyp参数导致的
> > > > > 
> > > > > 
> > > > > 我也是用scratch.yaml的超参训练，s=1000，才剪枝成功
> > > > 
> > > > 
> > > > 稀疏scale不应该是小于1吗，类似于0.01这种，1000也可以？
> > > 
> > > 
> > > 是啊，不试不知道啊
> > 
> > 
> > 那你稀疏训练的时候模型性能衰减的还能接受吗我的25差不多还行 再往上加就直接没精度了
> 
> mAP从0.87降到了0.8，还可以接受

为什么f1比较低，还是说这类任务基本只关注map就行

**Comment by seeyouagain111** [comment]
> > > > > > > > > 大多集中在0.7以上就是几乎所有值都大于0.7，而你这里迭代300次以后大部分值都在0.5以下。
> > > > > > > > > 那么如何解决稀疏度不够呢
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我的做法是减小学习率和压缩率
> > > > > > > 
> > > > > > > 
> > > > > > > 我尝试了不同的sr（从0.0001-0.001-0.01-1-5-10-。。。-5000）最后发现无论稀疏训练后map衰减到多少 剪枝后结果都是0，然后发现是因为我改了hyp参数的缘故，使用scratch的就没有这种问题 ，但问题是我的数据集是我自己跑的超参数，用我自己的超参数一旦剪枝就没有map了 所以不知道是不是因为你换了hyp参数导致的
> > > > > > 
> > > > > > 
> > > > > > 我也是用scratch.yaml的超参训练，s=1000，才剪枝成功
> > > > > 
> > > > > 
> > > > > 稀疏scale不应该是小于1吗，类似于0.01这种，1000也可以？
> > > > 
> > > > 
> > > > 是啊，不试不知道啊
> > > 
> > > 
> > > 那你稀疏训练的时候模型性能衰减的还能接受吗我的25差不多还行 再往上加就直接没精度了
> > 
> > 
> > mAP从0.87降到了0.8，还可以接受
> 
> 为什么f1比较低，还是说这类任务基本只关注map就行

关注precision跟recall还有mAP就够了，你F1特别低的话可能是置信度阈值的原因

**Comment by ZJU-lishuang** [comment]
> https://github.com/ZJU-lishuang/yolov5/blob/dfa8a7f1b6be19503b76b0d918deaeee8618d7ab/utils/general.py#L596
> 
> 这一行提示无法找到anchor_vec ，请问你没遇到过吗

使用DP mode会遇到该问题，使用DDP mode不会遇到该问题，多卡时使用DDP mode

**Comment by dpk3** [comment]
> > > > > > 
> > > > > > 
> > > > > > 稀疏scale不应该是小于1吗，类似于0.01这种，1000也可以？
> > > > > 
> > > > > 
> > > > > 是啊，不试不知道啊
> > > > 
> > > > 
> > > > 那你稀疏训练的时候模型性能衰减的还能接受吗我的25差不多还行 再往上加就直接没精度了
> > > 
> > > 
> > > mAP从0.87降到了0.8，还可以接受
> > 
> > 
> > 为什么f1比较低，还是说这类任务基本只关注map就行
> 
> 关注precision跟recall还有mAP就够了，你F1特别低的话可能是置信

**Comment by Heavenbest** [comment]
你好，我这边将剪枝后的模型进行微调，最后测试时显示错误，module AttributeError  :LeakyReLU object has no attribute in_channels. ，这个错误怎么解决呀？

**Comment by ZJU-lishuang** [comment]
#12 里面解决了，你可以看一下，最近忙其它项目，暂时没更新这里 
@Heavenbest

**Comment by Heavenbest** [comment]
@ZJU-lishuang 好的，谢谢，已解决
