### ISSUE TITLE
稀疏训练没有效果 bn_weights/hist 不能接近1

### ISSUE THREAD

**Issue by zimuyuan** [ZJU-lishuang/yolov5_prune#61]
我在使用你的代码的过程中，在稀疏训练阶段，150 个 epoch 没有效果 bn_weights/hist 不能接近 1 。似乎没有起到稀疏训练的效果。用的是 代码中的 yolov5s_v4 的网络结构和预训练权重，数据集用的 是coco128 图片比较少，想先试试流程能不能跑通下来。
![image](https://user-images.githubusercontent.com/40883979/137585350-af20e35f-a434-41a3-ab55-50e13829d978.png)

**Comment by ZJU-lishuang** [comment]
coco128目前稀疏未成功过，推测是数据集规模过小

**Comment by zimuyuan** [comment]
好的，那我试试其他数据集对比看看。
