### ISSUE TITLE
项目该更新了，现在都6.0版本yolov5了，作者加把劲

### ISSUE THREAD

**Issue by futureflsl** [ZJU-lishuang/yolov5_prune#63]
项目该更新了，现在都6.0版本yolov5了

**Comment by mx2013713828** [comment]
yolov5一个月push这么多，普通人怎么可能跟得上更新啊，作者也要有自己的工作啊

**Comment by ZJU-lishuang** [comment]
welcome PR

**Comment by Hazel-Xiang** [comment]
> welcome PR

请问我如果想在yolov5.5.0版本的基础上蒸馏，应该怎么修改呢？请问作者大大可以给个思路吗

**Comment by ZJU-lishuang** [comment]
@Hazel-Xiang 首先看一篇蒸馏的经典论文，了解一下大概的做法。
然后主要看train.py文件，和原来的对比看不通的地方。主要是改train.py就好了。

**Comment by ZJU-lishuang** [comment]
目前yolov5没什么奇怪的层，搭建出cfg的网络结构后就应该没什么大问题。之前主要是BottleneckCSP模块导致改动添加了较多地方的代码，目前该模块也换为了友好的C3模块。更新大概就是体力活和踩点小坑，这个更新时间就不定了。

welcome PR 😄

**Comment by Gumpest** [comment]
> 目前yolov5没什么奇怪的层，搭建出cfg的网络结构后就应该没什么大问题。之前主要是BottleneckCSP模块导致改动添加了较多地方的代码，目前该模块也换为了友好的C3模块。更新大概就是体力活和踩点小坑，这个更新时间就不定了。
> 
> welcome PR 😄

哈哈哈 期待

**Comment by ZJU-lishuang** [comment]
@futureflsl @Gumpest 更新了第六版本的剪枝了，支持更多的网络结构，也解决了多卡的问题

**Comment by Gumpest** [comment]
方便加作者的联系方式吗~

**Comment by ZJU-lishuang** [comment]
@Gumpest 可以

**Comment by Gumpest** [comment]
Wechat：18351209291
