### ISSUE TITLE
您好，请问yolov5剪枝后的速度能达到多少呢？

### ISSUE THREAD

**Issue by mx2013713828** [ZJU-lishuang/yolov5_prune#64]
模型大小和速度能到多少呢？
有个任务需求，在找一个实践，想先问一下大佬。
万分感谢。

**Comment by ZJU-lishuang** [comment]
https://github.com/ZJU-lishuang/yolov5_prune/blob/v4/tk1_time.xls

**Comment by ZJU-lishuang** [comment]
可以对标参考一下
