### ISSUE TITLE
调整三个参数 稀疏度一直不变

### ISSUE THREAD

**Issue by rachel-chennn** [ZJU-lishuang/yolov5_prune#69]
按照您在其他问题里的回复，我在常规训练之后进行稀疏训练。
但是不管我怎么调整  s(尝试了0.0001到5000)，batchsize(尝试了4到16)，epoch(尝试了100到200)
训练过程中的可视化都是下图的情况，稀疏度一直不能接近0，请问是什么可能原因呢？

![5acbc0f93df814948d5ebb6ae8bfb89](https://user-images.githubusercontent.com/78188285/144963130-1789ea70-b95a-4195-b6a9-a1ffb0ff7524.png)

**Comment by rachel-chennn** [comment]
我的数据集有900张图片

**Comment by ZJU-lishuang** [comment]
数据集规模小了

**Comment by rachel-chennn** [comment]
> 数据集规模小了

请问数据集大概在多少张合适呢

**Comment by ZJU-lishuang** [comment]
可以参考示例

**Comment by rachel-chennn** [comment]
> 可以参考示例

还想请问一下，可以用之前自己训练的yolov5权重放到项目里，然后从稀疏化训练那一步开始嘛
