### ISSUE TITLE
咨询个问题哈，通过这种剪枝，那么删除了一些层和通道，那么会导致转换ncnn有些问题吧，相当远原网络结构变了

### ISSUE THREAD

**Issue by EricHuiK** [ZJU-lishuang/yolov5_prune#7]

**Comment by ZJU-lishuang** [comment]
If you want to keep the network structure the same ,you can refer to [Pruning/Sparsity Tutorial](https://github.com/ultralytics/yolov5/issues/304).
this project provides the the pruned network structure in cfg.
