### ISSUE TITLE
关于稀疏后剪枝

### ISSUE THREAD

**Issue by rachel-chennn** [ZJU-lishuang/yolov5_prune#72]
请问，我稀疏训练的结果显示 mAP跟正常训练的差不多，如下图

![image](https://user-images.githubusercontent.com/78188285/145231548-7f011df6-a814-48cf-bbe2-3e852744a077.png)

但是放进剪枝读取的时候，就读取到下图这样

![image](https://user-images.githubusercontent.com/78188285/145231771-5f0a3e35-8641-4703-8a39-b0f73f5eff74.png)

mAP变很小，于是我剪枝的结果mAP是零，请问是怎么回事呢

附上我稀疏训练的可视化

![d374cd4b0f143ea9a74ddfd1507bde6](https://user-images.githubusercontent.com/78188285/145232074-e47f553d-61bf-4b0f-904b-0fc246b55c59.png)

谢谢！！！

**Comment by ZJU-lishuang** [comment]
稀疏度不够吧，剪枝比例超了。稀疏度那里0.5的边界

**Comment by rachel-chennn** [comment]
> 稀疏度不够吧，剪枝比例超了。稀疏度那里0.5的边界

那请问大佬，怎样判断稀疏度是不是够了呢，看图嘛？还是看什么指标呢？我后来稀疏成下面图的结果，放进剪枝也还是test the origin model时map就变为很小了，跟上边贴的图结果差不多。
![image](https://user-images.githubusercontent.com/78188285/145501854-531bab24-e7ea-444c-81cb-d4fa51102afa.png)
再次感谢！！！

**Comment by ZJU-lishuang** [comment]
稀疏训练--prune设置的是1吗

**Comment by rachel-chennn** [comment]
> 稀疏训练--prune设置的是1吗

参数为--prune 0 --s 0.002 --epoch 350
感谢您的回复！！

**Comment by ZJU-lishuang** [comment]
我再看看问题吧，prune_yolov5s.py没怎么用，看看和测试函数怎么没搭上

**Comment by rachel-chennn** [comment]
> 我再看看问题吧，prune_yolov5s.py没怎么用，看看和测试函数怎么没搭上

非常感谢您，辛苦啦！！

**Comment by ZJU-lishuang** [comment]
你可以先试试其它的剪枝策略

**Comment by rachel-chennn** [comment]
> 你可以先试试其它的剪枝策略

好的！其他剪枝策略有您优先推荐的嘛？我现在就尝试一下

**Comment by ZJU-lishuang** [comment]
slim_prune_yolov5s_8x.py，其实除prune_yolov5s.py外其它的稀疏策略一致，prune_yolov5s.py实际不实用。

**Comment by rachel-chennn** [comment]
好的，十分感谢您一直及时的回复~ 我这就去试

**Comment by ZJU-lishuang** [comment]
我使用项目里的数据集跑prune_yolov5s.py没问题。稀疏模型
[last.zip](https://github.com/ZJU-lishuang/yolov5_prune/files/7690777/last.zip)
后缀zip改为pt

**Comment by rachel-chennn** [comment]
好的感谢！那估计是我的数据集太少了
