### ISSUE TITLE
通道减枝失败

### ISSUE THREAD

**Issue by CMelo97** [ZJU-lishuang/yolov5_prune#74]
![图片](https://user-images.githubusercontent.com/87006484/146719251-f23fb48a-5a24-4d04-921d-27fcc2ae421a.png)
作者你好，有空的话能帮我看看这个问题吗？在自己的数据集上，基础训练和稀疏训练都已经复现，在通道减枝策略1中出现了上述问题。

**Comment by ZJU-lishuang** [comment]
少打了什么东西吧，自己debug一下
