### ISSUE TITLE
STEP3:通道剪枝策略一 模型加载不了

### ISSUE THREAD

**Issue by ztrong-forever** [ZJU-lishuang/yolov5_prune#80]
![image](https://user-images.githubusercontent.com/62659186/148346445-c7b1a059-e525-463f-bb8e-d4ec68fcf4a3.png)
您好大佬！我将剪枝后的模型保存后，想在val.py中加载模型测试效果，可是一直加载不了

**Comment by ZJU-lishuang** [comment]
参考该[做法](https://github.com/ZJU-lishuang/yolov5_prune/blob/v6/slim_prune_yolov5s_8x.py#L55)
剪枝模型保存的不是yolov5格式的模型，需要转一下

**Comment by ztrong-forever** [comment]
好的，感谢答复！！
