### ISSUE TITLE
多GPU下finetune报错

### ISSUE THREAD

**Issue by thunder95** [ZJU-lishuang/yolov5_prune#89]
torch.nn.modules.module.ModuleAttributeError: 'Model' object has no attribute 'module_list'

注释掉后yololayer也会报错

都注释掉后，finetune会出现map为NAN， 请教下大佬怎么破啊

**Comment by thunder95** [comment]
使用单卡训练的时候， soft的值很高，而且训练少量steps之后，就都变成nan了

**Comment by ZJU-lishuang** [comment]
多卡训练用torch.distributed.run

**Comment by ZJU-lishuang** [comment]
蒸馏有问题就先不要用蒸馏选项

**Comment by thunder95** [comment]
@ZJU-lishuang 好的 谢谢大哥 好人一生平安
