### ISSUE TITLE
yolov5s_hand.yaml内容与原版yolov5s.yaml不一致

### ISSUE THREAD

**Issue by eeric** [ZJU-lishuang/yolov5_prune#9]
yolov5s_hand.yaml的内容是对模型结构的重新定义，是分拆的吧，与原版yolov5内容不一致，这样就得以你定义的yaml重新训练模型，在稀疏训练，再剪枝和微调。
能不能直接用原版yolov5.yaml预训练的模型，直接稀疏训练，再剪枝和微调呢？

**Comment by EricHuiK** [comment]
我也发现了好多错误，没法复现

**Comment by ZJU-lishuang** [comment]
The different between yolov5s_hand.yaml and yolov5s.yaml only is the num of class.
I have provided my training file in google cloud disk.
I think it is easy to reproduce it and make a compare.
If there is a bug, please show me the code.Talk is cheap.

**Comment by ZJU-lishuang** [comment]
@eeric Training the coco dataset need a lot of computing resources.
You can try it by yourself.

**Comment by eeric** [comment]
你为什么不用原版yolov5s.yaml训练呢，你可以把类数量修改吧。如果你按照它原来的模型设计，可以清楚看到如何准确找到BN层，而对后面的相邻层通道进行剪枝吧

**Comment by ZJU-lishuang** [comment]
The different between yolov5s_hand.yaml and yolov5s.yaml only is the num of class.The network structure is the same.
Can you tell me the different between the [yolov5s_hand.yaml](https://github.com/ZJU-lishuang/yolov5/blob/master/models/yolov5s_hand.yaml) and [yolov5s.yaml](https://github.com/ZJU-lishuang/yolov5/blob/master/models/yolov5s.yaml) except the num of class.

**Comment by eeric** [comment]
我是希望你能基于原版.yaml做成一套剪枝方法，而不是等同于把原网络结构拆解，再按推断顺序不变的方式吧。

**Comment by ZJU-lishuang** [comment]
I have not a good idea for the analysis of network structure in yaml.The index of layer in yaml is not friendly to prune.
We need to build another set of tools to do it.
But this project is based on [tanluren/yolov3-channel-and-layer-pruning](https://github.com/tanluren/yolov3-channel-and-layer-pruning).

**Comment by eeric** [comment]
ok, thanks!

**Comment by ZJU-lishuang** [comment]
First time I have a try on yaml and find it unfriendly for the terrible layer name.Just like layer_name[].BottleneckCSP.cv1.conv，arr and dict are mixed together.It bad for prune adjacent channel.
