### ISSUE TITLE
对稀疏训练bn权重更新的一点疑问

### ISSUE THREAD

**Issue by thunder95** [ZJU-lishuang/yolov5_prune#91]
大佬，我看了下你的源码，发现只是对cfg_model进行L1正则化， 但是训练的model是通过yaml加载的， 这里是不是只正则化cfg_model的bn权重，但是并没有更新原model的bn权重，后续剪枝加载的预训练权重是model的，而不是稀疏过后cfg_model的。

不知道是不是我理解错了，这里稀疏训练貌似没有达到预期。请大佬帮忙解惑。

**Comment by ZJU-lishuang** [comment]
https://github.com/ZJU-lishuang/yolov5_prune/blob/v6/utils/model_transfer.py#L74

**Comment by thunder95** [comment]
> https://github.com/ZJU-lishuang/yolov5_prune/blob/v6/utils/model_transfer.py#L74

大哥新年好， 谢谢大哥这么迅猛的回复， 貌似明白了，您将cfg_model的网络层内存地址映射到model了吧，所以修改cfg_model就会同时修改model，是不是这样理解的？

**Comment by ZJU-lishuang** [comment]
对，简单理解就是内存地址一样，外面取了两个不同的名字

**Comment by thunder95** [comment]
谢谢
